apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bcdmnzd62-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bcdmnzd62-nodejs 
  name: bcdmnzd62-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bcdmnzd62-nodejs 
